name: Build & Test

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "pnpm-lock.yaml"
      - "**/build.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4

      - name: Install Packages.
        run: pnpm i --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
