name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: The semver release type
        type: choice
        default: patch
        required: true
        options:
          - patch
          - minor
          - major

      tag:
        description: Release Tag
        type: string
        required: false

      release_name:
        description: The release name.
        type: string
        required: false

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load secret
        id: load-op
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          NPM_TOKEN: "op://Actions/shared/NPM_TOKEN"

      - name: Set Version for Unreleased
        id: changelog
        uses: jelmore1674/build-changelog@v1
        with:
          release_type: ${{ inputs.release_type }}
          version: ${{ inputs.tag }}
          skip_commit: true

      - name: Create Release
        id: create_release
        uses: jelmore1674/release-semver-action@v1
        with:
          tag_name: ${{ steps.changelog.outputs.release_version || inputs.tag }}
          release_name: ${{ steps.changelog.outputs.release_version || inputs.tag }}
          body: ${{ steps.changelog.outputs.notes }}
          update_package_json: true

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install Packages.
        run: pnpm i --frozen-lockfile
      - name: Build
        run: pnpm build
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ steps.load-op.outputs.NPM_TOKEN }}
          access: public
