name: Release

on:
  schedule:
    - cron: "25 4 * * 2"

  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag
        type: string
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get tags
        run: git fetch --tags origin
      - name: Get latest tag
        id: get_tag
        run: |
          if [[ -n $(git tag --points-at HEAD) ]]; then
            echo "latest_tag=false" >> $GITHUB_OUTPUT
          else
            echo "latest_tag=true" >> $GITHUB_OUTPUT
          fi

      - name: Load secret
        if: ${{ steps.get_tag.outputs.latest_tag == 'true' }}
        id: load-op
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GH_APP_KEY: "op://Actions/GH_APP_KEY/private key"
          APP_ID: op://Actions/shared/APP_ID

      - name: Get Token
        if: ${{ steps.get_tag.outputs.latest_tag == 'true' }}
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ steps.load-op.outputs.APP_ID }}
          application_private_key: ${{ steps.load-op.outputs.GH_APP_KEY }}
          revoke_token: true

      - name: Create Release
        id: create_release
        if: ${{ steps.get_tag.outputs.latest_tag == 'true' }}
        uses: jelmore1674/release-semver-action@v1
        with:
          auto_version: true
          tag_name: ${{ inputs.tag }}
          release_name: ${{ inputs.tag }}
          update_package_json: true
          set_changelog_version: true
          release_notes_from_changelog: true
          token: ${{ steps.get_workflow_token.outputs.token }}
          commit_message: Bump version $version [skip ci]
